FORMAT: 1A

# SV Information API
Su función general es proporcionar en un objeto `JSON` información detallada
acerca de una película o una serie en particular haciendo uso del API
proporcionada por IMDb (`https://www.imdb.com/`).

# Group Information
Recursos de **SV Information API**.

## Information [/information{?t}]
### Obtiene información de una película [GET]

+ Parameters
    + t (required, string) ... Es el título de la película a consultar.

+ Request (application/x-www-form-urlencoded)

        t=Stranger+things

+ Response 200 (application/json)

        {
            "Title": "Stranger Things",
            "Year": "2016–",
            "Rated": "TV-14",
            "Released": "15 Jul 2016",
            "Runtime": "55 min",
            "Genre": "Drama, Fantasy, Horror",
            "Director": "N/A",
            "Writer": "Matt Duffer, Ross Duffer",
            "Actors": "Winona Ryder, David Harbour, Finn Wolfhard, Millie Bobby Brown",
            "Plot": "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying forces in order to get him back.",
            "Language": "English",
            "Country": "USA",
            "Awards": "Nominated for 2 Golden Globes. Another 7 wins & 43 nominations.",
            "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEzMDAxOTUyMV5BMl5BanBnXkFtZTgwNzAxMzYzOTE@._V1_SX300.jpg",
            "Ratings": [
                {
                    "Source": "Internet Movie Database",
                    "Value": "9.0/10"
                }
            ],
            "Metascore": "N/A",
            "imdbRating": "9.0",
            "imdbVotes": "289,958",
            "imdbID": "tt4574334",
            "Type": "series",
            "totalSeasons": "2",
            "Response": "True"
        }
